language: ruby
rvm:
  - 2.1.2

cache:
  bundler: true
  directories:
    - node_modules

before_script:
  - npm install -g webpack
  - npm install

script:
  - npm test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
