# Site settings
title: CodeHeaven
email: codeheaven.io@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codeheaven.io/"
author: codeheaven
lang: en

github_username: codeheaven-io
twitter_username: codeheaven_io

# 'none' has the same effect as /:categories/:title.html
permalink: /:categories/:title

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Google Analytics info
google_universal_analytics: UA-60941725-1
google_universal_analytics_cookiedomain: auto

exclude: [vendor]

gems:
  - octopress-escape-code
  - jekyll-sitemap
  - rouge
