# Site settings
title: CodeHeaven
email: codeheaven.io@gmail.com
description: >
  Cause your code takes me to paradise.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://codeheaven.io" # the base hostname & protocol for your site
url: "http://localhost:4000/" # the base hostname & protocol for your site
author: codeheaven
lang: en

github_username: codeheaven-io
twitter_username: codeheaven_io

# Build settings
markdown: kramdown

# google_universal_analytics: TODO
# google_universal_analytics_cookiedomain: auto

gems:
  - octopress-escape-code
  - jekyll-sitemap

headers:
  - filename: '^assets.*\.js$'
    expires: '+3 years'
    cache_control: 'max-age=94608000'
    content_type: 'application/javascript'
  - filename: '^assets.*\.css$'
    expires: '+3 years'
    cache_control: 'max-age=94608000'
    content_type: 'text/css'
